# File: .github/workflows/ci.yml

name: Basic CI Pipeline
on: workflow_dispatch
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, World!"
      - name: Run multiple CLI commands
        run: |
          echo "Starting multi-line commands"
          uname -a
          echo "Listing files:"
          ls -la
          echo "Done"
  job2:
    needs: job1
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest`,macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, World!"
      - name: Run multiple CLI commands
        run: |
          echo "Starting multi-line commands"
          uname -a
          echo "Listing files:"
          ls -la
          echo "Done" > testfile.txt
          cat testfile.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
            name: my-testfile-artifact
            path: testfile.txt
  job3:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
            name: my-testfile-artifact
      - name: Display artifact content
        run: cat testfile.txt